# This is a basic workflow that is manually triggered

name: 02 - Evento issue

on:
  push:
    paths-ignore:
      - '*.md'
  issues:
    types: 
      - opened


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Hola Nuevo Hola mundo
      run: echo "¡Hola nuevo Hola mundo"